DROP TABLE IF EXISTS author_book;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS author;
DROP SEQUENCE IF EXISTS author_seq;
DROP SEQUENCE IF EXISTS book_seq;

CREATE SEQUENCE author_seq AS INTEGER START WITH 100000;
CREATE SEQUENCE book_seq AS INTEGER START WITH 100000;

CREATE TABLE author
(
    id       INTEGER GENERATED BY DEFAULT AS SEQUENCE author_seq PRIMARY KEY,
    name     VARCHAR(255)                    NOT NULL,
    surname  VARCHAR(255)                    NOT NULL,
    birthday DATE                            NOT NULL,
    sex      VARCHAR(10) DEFAULT 'UNDEFINED' NOT NULL
);

CREATE TABLE book
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE book_seq PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    publication_year DATE         NOT NULL,
    publishing_house VARCHAR(255) NOT NULL
);

CREATE TABLE author_book
(
    author_id INTEGER NOT NULL,
    book_id   INTEGER,
    UNIQUE (author_id, book_id),
    FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE
);